import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthenticationWrapper from "@/lib/wrappers/auth-wrapper";
import Providers from "@/components/providers/progress-provider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { getUser } from "@/lib/user";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{


  return (
  
      <html lang="en" className=" bg-[rgb(25,25,25)]">      
        <body className={inter.className}>
            {children}
        </body>
      </html>
    
  );
}
